In [3]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, img_as_float
import cv2

In [4]:
img = img_as_float(io.imread('test.png', as_gray=True))
img

array([[0.99719451, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.99719451, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.99719451, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ]], shape=(712, 623))

In [7]:
kernel = np.ones((5, 5), np.float32) / 25
kernel

array([[0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.04, 0.04]], dtype=float32)

In [6]:
gaussion_kernel = np.array([[1/16, 1/8, 1/16],
                            [1/8, 1/4, 1/8],
                            [1/16, 1/8, 1/16]])
gaussion_kernel

array([[0.0625, 0.125 , 0.0625],
       [0.125 , 0.25  , 0.125 ],
       [0.0625, 0.125 , 0.0625]])

In [8]:
conv_img_cv2 = cv2.filter2D(img, -1, kernel, borderType=cv2.BORDER_CONSTANT)
conv_img_cv2_gaussian = cv2.filter2D(img, -1, gaussion_kernel, borderType=cv2.BORDER_CONSTANT)

In [11]:
cv2.imshow('Original Image', img)
cv2.imshow('Convolution with Kernel', conv_img_cv2)
cv2.imshow('Convolution with Gaussian Kernel', conv_img_cv2_gaussian)
cv2.waitKey(0)
cv2.destroyAllWindows()

Object `cv.destroyAllWindows()` not found.
